<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["customers", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit customers
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "customers/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCstStatusFlag" class="col-sm-2 control-label">Cst Of Status Of Flag</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cst_status_flag", "type" => "number", "class" => "form-control", "id" => "fieldCstStatusFlag"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCstNameLast" class="col-sm-2 control-label">Cst Of Name Of Last</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cst_name_last", "size" => 30, "class" => "form-control", "id" => "fieldCstNameLast"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCstNameFirst" class="col-sm-2 control-label">Cst Of Name Of First</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["cst_name_first", "size" => 30, "class" => "form-control", "id" => "fieldCstNameFirst"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
