<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
    [
        "customers/create",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>


<div class="col-md-10 mt-4" style="width: 50rem;">

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Crear cliente</h5>

            <div class="form-group">
                <label for="fieldCstStatusFlag">Cst Of Status Of Flag</label>

                <?php echo $this->tag->textField(["cst_status_flag", "type" => "number", "class" => "form-control", "id" => "fieldCstStatusFlag"]) ?>

            </div>

            <div class="form-group">
                <label for="fieldCstNameLast">Cst Of Name Of Last</label>
                <div class="col-sm-10">
                    <?php echo $this->tag->textField(["cst_name_last", "size" => 30, "class" => "form-control", "id" => "fieldCstNameLast"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldCstNameFirst">Cst Of Name Of First</label>
                <div class="col-sm-10">
                    <?php echo $this->tag->textField(["cst_name_first", "size" => 30, "class" => "form-control", "id" => "fieldCstNameFirst"]) ?>
                </div>
            </div>


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-info"]) ?>
                    <?php echo $this->tag->linkTo(["customers", "Volver", "class" => "btn btn-dark"]) ?>
                </div>
            </div>


            <?php echo $this->tag->endForm(); ?>
        </div>
    </div>

</div>