<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php

use Phalcon\Tag; ?>





<?php echo $this->getContent(); ?>

<div class="container mt-4">
    <h1>Resultados</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Cst</th>
                <th>Cst Of Status Of Flag</th>
                <th>Cst Of Name Of Last</th>
                <th>Cst Of Name Of First</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($page->items as $customer) : ?>
                <tr>
                    <td><?php echo $customer->cst_id ?></td>
                    <td><?php echo $customer->cst_status_flag ?></td>
                    <td><?php echo $customer->cst_name_last ?></td>
                    <td><?php echo $customer->cst_name_first ?></td>

                    <td><?php echo $this->tag->linkTo(["customers/edit/" . $customer->cst_id, "Editar"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["customers/delete/" . $customer->cst_id, "Borrar"]); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="container">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("customers/search", "Primero") ?></li>
                <li>&nbsp;<?php echo $this->tag->linkTo("customers/search?page=" . $page->before, "Anterior") ?></li>
                <li>&nbsp;<?php echo $this->tag->linkTo("customers/search?page=" . $page->next, "Siguiente") ?></li>
                <li>&nbsp;<?php echo $this->tag->linkTo("customers/search?page=" . $page->last, "Último") ?></li>
            </ul>
        </nav>
    </div>
</div>

<div class="container">

    <?php echo $this->tag->linkTo(["customers/index", "Volver", "class" => "btn btn-dark"]); ?>
    <?php echo $this->tag->linkTo(["customers/new", "Crear", "class" => "btn btn-info"]); ?>

</div>